name: Deploy to GCS

on:
  push:
    branches: [ main ]  # or "master" if that's your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Upload files to GCS
        run: |
          gsutil -m cp -r ./ gs://akshatashenoy2311-blog
